server:
#  port: ${proxyPort}
  port: 9527


## http://localhost:8088/api/hello
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
      - id: order
#        uri: ${backendService}
        uri:  lb://order-service
        predicates:
#        - Path=${proxyContext}
         - Path=/order/**
logging:
  level:
    io.github.kimmking: ERROR
    org: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
